CREATE TABLE IF NOT EXISTS countries
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    country_name VARCHAR(30) NOT NULL UNIQUE

);
CREATE TABLE IF NOT EXISTS rooms
(
    id         BIGINT PRIMARY KEY AUTO_INCREMENT,
    room_name VARCHAR(30) NOT NULL UNIQUE,
    country_id BIGINT NOT NULL,
    FOREIGN KEY (country_id) REFERENCES countries (id)

);
CREATE TABLE IF NOT EXISTS lamps
(
    id    BIGINT PRIMARY KEY AUTO_INCREMENT,
    room_id BIGINT NOT NULL,
    state BOOLEAN DEFAULT (false),
    FOREIGN KEY (room_id) REFERENCES rooms (id)

);



